---
title: "Turbidity Behavioral Trials Data Tidying"
author: "Hannah Anderson"
date: "2024-02-09"
output: pdf_document
---

Description of Orphan Project here?

```{r setup, include=FALSE}
library(tidyverse)

setwd("C://Users/hande/Documents/R/fluctuating-turbidity")
emily_data <- read_csv("flux_turb_behav_trials_Emily.csv")
sana_data <- read_csv("flux_turb_behav_trials_Sana.csv")

#the tank IDs in each treatment
fluxtanks <- c("tank4-1", "tank7-2", "tank6-1", "tank6-3", "tank1-3",
               "tank1-2", "tank2-3")
stabletanks <- c("tank8-2", "tank3-1", "tank5-3", "tank6-2", "tank1-1",
                 "tank8-1", "tank7-1", "tank2-2")
cleartanks <- c("tank8-3", "tank3-2", "tank3-3", "tank4-3", "tank7-3",
                "tank4-2", "tank5-1", "tank2-1")
```


## Cleaning base data

Fixing any discrepancies between scorers as well as any mistakes or clarity
problems in the original datasets.

```{r tidying}
#trimming down the dataframes so they only contain useful columns
emily_trim <- emily_data[,c(9:10,14,19)]
sana_trim <- sana_data[,c(9:10,13,18)]

#changing the column names to be more R friendly
sharecol <- c("tankID", "recording", "behavior", "duration_s")
colnames(emily_trim) <- sharecol
colnames(sana_trim) <- sharecol

#making sure the tank IDs are consistent between the two scorers
sana_trim$tankID <- gsub("_", "-", sana_trim$tankID)
sana_trim$tankID <- paste0("tank", sana_trim$tankID)

#combining the files from the different scorers
all_data <- rbind(emily_trim, sana_trim)

#pulling the feeding trial data from the compiled data set
feeding <- all_data %>%
           filter(behavior == "feeding")
#pulling the shelter trial data from the compiled data set
shelter <- all_data %>%
           filter(behavior %in% c("shelter_approach", "1_fish_shelter",
                                  "2_fish_shelter", "3_fish_shelter",
                                  "4_fish_shelter"))
#pulling the color preference trial data from the compiled dataset
color <- all_data %>%
         filter(behavior %in% c("swim_border_yellow", "swim_over_yellow",
                                "swim_border_red", "swim_over_red",
                                "swim_border_purple", "swim_over_purple",
                                "swim_border_blue", "swim_over_blue"))

#creating a complete recording list from the feeding trial's nearly-complete
#list to fill in any missing values from other trials
all_rec <- feeding[,1:2]
missing <- c("tank6-1", 2)
all_rec <- rbind(all_rec, missing)
```


## Feeding Trial Data Cleaning

```{r feeding}
#adding in NAs for the feeding trial that was mistakenly not recorded
missing <- c("tank6-1", 2, "feeding", NA)
feeding <- rbind(feeding, missing)

#adding the treatment conditions
feeding$treatment <- feeding$tankID %>%
                     fct_collapse(flux = fluxtanks,
                                  stable = stabletanks,
                                  clear = cleartanks)

#renaming the recording values to be more intuitive
feeding$recording <- as.numeric(feeding$recording)
feeding <- feeding %>%
           mutate(recording = case_match(recording, 1 ~ "morning",
                                                    2 ~ "afternoon"))

#writing the cleaned feeding trial data to .csv
write_csv(feeding, "flux_turb_feeding_trial.csv")
```


## Shelter Trial Data Cleaning

```{r shelter}
#summing the duration of time the shelter was occupied by each density level of
#fish and counting the number of times the shelter was that density for each
#trial
shelter_dens <- shelter %>%
               filter(behavior != "shelter_approach") %>%
               group_by(tankID, recording, behavior) %>%
               summarize(duration_s = sum(duration_s),
                         enter_exit = as.numeric(table(behavior)))
#adding up the shelter durations to get a total time a shelter was occupied and
#the total number of times the shelter was entered or exited per trial
shelter_dura <- shelter_dens %>%
               group_by(tankID, recording) %>%
               summarize(sheltered_time_s = sum(duration_s),
                         enter_exit = sum(enter_exit))

#prepping the shelter approach latency to be combined with the summarized
#shelter data
shelter_app <- shelter %>%
               filter(behavior == "shelter_approach")
shelter_app <- shelter_app[,c(1:2,4)]
shelter_app <- shelter_app %>%
               rename_at("duration_s", ~"approach_time_s")

#combining the shelter approach latency and summarized shelter data into a
#single dataframe
shelter_all <- merge(shelter_dura, shelter_app, by = c("tankID", "recording"),
                     all = TRUE)
#replacing the NAs in the shelter use duration and enter/exit columns with true
#zeros (the shelter was not used for these trials)
shelter_all <- shelter_all %>%
               replace(is.na(.), 0)

#adding the treatment conditions
shelter_all$treatment <- shelter_all$tankID %>%
                         fct_collapse(flux = fluxtanks,
                                      stable = stabletanks,
                                      clear = cleartanks)

#renaming the recording values to be more intuitive
shelter_all <- shelter_all %>%
               mutate(recording = case_match(recording, 1 ~ "morning",
                                                        2 ~ "afternoon"))

#writing the cleaned shelter trial data to .csv
write_csv(shelter_all, "flux_turb_shelter_trial.csv")
```


## Color Preference Trial

``` {r color}
#counting the number of times the fish swam over each color
color_over <- color %>%
              filter(behavior %in% c("swim_over_yellow", "swim_over_red",
                                     "swim_over_purple", "swim_over_blue")) %>%
              group_by(tankID, recording, behavior) %>%
              summarize(swim_over = as.numeric(table(behavior)))
#counting the number of times the fish swam around the border of each color
color_border <- color %>%
                filter(behavior %in% c("swim_border_yellow", "swim_border_red",
                                       "swim_border_purple", "swim_border_blue"
                                       )) %>%
                group_by(tankID, recording, behavior) %>%
                summarize(swim_border = as.numeric(table(behavior)))

#changing the names of the "behavior" column to be consistent between the border
#swim and swim over data
color_over <- color_over %>%
              mutate(behavior = case_match(behavior, 
                                           "swim_over_blue" ~ "blue",
                                           "swim_over_purple" ~ "purple",
                                           "swim_over_red" ~ "red",
                                           "swim_over_yellow" ~ "yellow"))
color_border <- color_border %>%
                mutate(behavior = case_match(behavior, 
                                           "swim_border_blue" ~ "blue",
                                           "swim_border_purple" ~ "purple",
                                           "swim_border_red" ~ "red",
                                           "swim_border_yellow" ~ "yellow"))

#combining the color trial data into a single dataframe
color_all <- merge(color_over, color_border, by = c("tankID", "recording",
                                                    "behavior"),
                   all = TRUE)
color_all <- color_all %>%
             rename_at("behavior", ~ "color")

#adding in the true zero values (which BORIS does not export)
color_complete <- color_all %>%
                  complete(tankID, recording, color, fill =
                                                     list(swim_over = 0,
                                                          swim_border= 0))

#adding the treatment conditions
color_complete$treatment <- color_complete$tankID %>%
                            fct_collapse(flux = fluxtanks,
                                         stable = stabletanks,
                                         clear = cleartanks)

#renaming the recording values to be more intuitive
color_complete <- color_complete %>%
                  mutate(recording = case_match(recording, 1 ~ "morning",
                                                           2 ~ "afternoon"))

#writing the cleaned color preference trial data to .csv
write_csv(color_complete, "flux_turb_color_trial.csv")
```