---
title: "BORIS Data Tidying"
author: "Hannah Anderson"
date: "2023-04-12"
output: pdf_document
---

## Setup

Our scorers used BORIS to score the behavior of fish in videos from four
different experiments: a chronic clay exposure, an acute clay exposure, a pond
dye with stirring exposure, and a pond dye without stirring exposure.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)

#the data files produced by our video scorers
longclay_isabella <- read_csv("chronic_clay_BORIS_Isabella.csv")
longclay_izma <- read_csv("chronic_clay_BORIS_Izma_HMAedited.csv")
shortclay_grace <- read_csv("acute_clay_BORIS_Grace.csv")
shortclay_sana <- read_csv("acute_clay_BORIS_Sana.csv")
dyestir_ryan <- read_csv("stir_dye_BORIS_Ryan_HMAedited.csv")
dye_grace <- read_csv("dye_BORIS_Grace.csv") #includes both dye experiments
nostir_ryan <- read_csv("nostir_dye_BORIS_Ryan_HMAedited.csv")
```



```{r tidying}
#Grace included two experiments in her dye file, so I'm separating them
dyestir_grace <- dplyr::filter(dye_grace, grepl("YES", `Media file`))
nostir_grace <- dplyr::filter(dye_grace, grepl("NO", `Media file`))

#trimming down the data frames so they only contain useful columns
longclay_isabella <- longclay_isabella[,c(6:9,12)]
longclay_izma <- longclay_izma[,c(7:8,11,14,17)]
shortclay_grace <- shortclay_grace[,c(7:8,10,13,16)]
shortclay_sana <- shortclay_sana[,c(7:8,10,13,16)]
dyestir_ryan <- dyestir_ryan[,c(7:8,11,14,17)]
dyestir_grace <- dyestir_grace[,c(7:8,10,13,16)]
nostir_ryan <- nostir_ryan[,c(7:8,11,14,17)]
nostir_grace <- nostir_grace[,c(7:8,10,13,16)]

#changing column names to be universal for all experiments
sharecol <- c("tankID", "recording", "behavior", "behav_type", "duration_s")
colnames(longclay_isabella) <- sharecol
colnames(longclay_izma) <- sharecol
colnames(shortclay_grace) <- sharecol
colnames(shortclay_sana) <- sharecol
colnames(dyestir_grace) <- sharecol
colnames(dyestir_ryan) <- sharecol
colnames(nostir_grace) <- sharecol
colnames(nostir_ryan) <- sharecol

#Ryan's stirred dye file is missing the tankID and recording number for the
#tank 7-3, recording 3 video
dyestir_ryan$tankID[is.na(dyestir_ryan$tankID)] <- "7-3"
dyestir_ryan$recording[is.na(dyestir_ryan$recording)] <- 3
#Ryan also used two different behavior names than the others, consolidating
dyestir_ryan$behavior[dyestir_ryan$behavior == "chase"] <- "chasing"
dyestir_ryan$behavior[dyestir_ryan$behavior == "agg"] <- "agg_contact"
nostir_ryan$behavior[nostir_ryan$behavior == "Chasing"] <- "chasing"
nostir_ryan$behavior[nostir_ryan$behavior == "aggressive contact"] <- "agg_contact"
nostir_ryan$behavior[nostir_ryan$behavior == "lateral display"] <- "lat_display"


#some students' tank IDs got converted to dates, so converting them back here
datlength <- length(longclay_isabella$tankID)
for (i in 1:datlength) {
  str_hold <- strsplit(longclay_isabella$tankID[i], split = "/")
  longclay_isabella$tankID[i] <- paste(str_hold[[1]][1], str_hold[[1]][2],
                                       sep = "-")
}
datlength <- length(shortclay_sana$tankID)
for (k in 1:datlength) {
  str_hold <- strsplit(shortclay_sana$tankID[k], split = "/")
  shortclay_sana$tankID[k] <- paste(str_hold[[1]][1], str_hold[[1]][2],
                                    sep = "-")
}

#combining the files from different scorers for their shared experiments
longclay_all <- rbind(longclay_isabella, longclay_izma)
shortclay_all <- rbind(shortclay_grace, shortclay_sana)
dyestir_all <- rbind(dyestir_grace, dyestir_ryan)
nostir_all <- rbind(nostir_grace, nostir_ryan)

#adding a treatment condition column to the files missing it and also sex to the
#long clay experiment
longclay_all$treatment <- longclay_all$tankID %>%
                               fct_collapse(flux = c("5-3", "1-1", "4-3", "6-2",
                                                     "3-2", "5-1", "2-3", "8-3"),
                                            stable = c("2-1", "3-1", "6-1", "7-1",
                                                       "4-2", "2-2", "6-3", "7-2"),
                                            clear = c("7-3", "8-2", "8-1", "4-1",
                                                      "3-3", "1-3", "5-2", "1-2"))
longclay_all$sex <- longclay_all$tankID %>%
                         fct_collapse(female = c("5-3", "1-1", "4-3", "6-2",
                                                 "2-1", "3-1", "6-1", "7-1",
                                                 "7-3", "8-2", "8-1", "4-1"),
                                      male = c("3-2", "5-1", "2-3", "8-3",
                                               "4-2", "2-2", "6-3", "7-2",
                                               "3-3", "1-3", "5-2", "1-2"))
shortclay_all$treatment <- shortclay_all$tankID %>%
                           fct_collapse(flux = c("7-3", "3-1", "6-1", "6-2",
                                                   "4-1", "2-1", "7-2", "8-2"),
                                        stable = c("7-1", "3-3", "8-3", "3-2",
                                                     "6-3", "5-1", "1-3", "4-2"),
                                        clear = c("5-3", "1-2", "4-3", "2-2",
                                                    "1-1", "8-1", "2-3", "5-2"))
dyestir_all$treatment <- dyestir_all$tankID %>%
                         fct_collapse(flux = c("1-2", "3-3", "2-1", "4-3",
                                               "5-1", "6-1", "5-2", "3-1"),
                                      stable = c("4-2", "7-1", "6-3", "2-2",
                                                 "5-3", "8-3", "8-1", "2-3"),
                                      clear = c("7-2", "8-2", "7-3", "4-1",
                                                "3-2", "1-3", "1-1", "6-2"))
nostir_all$treatment <- nostir_all$tankID %>%
                        fct_collapse(flux = c("8-2", "5-1", "3-2", "1-1",
                                              "6-1", "4-3", "6-3", "1-2"),
                                     stable = c("3-1", "7-1", "3-3", "8-1",
                                                "2-3", "4-2", "4-1", "8-3"),
                                     clear = c("2-2", "2-1", "5-2", "7-3",
                                               "7-2", "5-3", "1-3", "6-2"))


#collapsing the behaviors into counts and durations
longclay_coll <- longclay_all %>%
                 group_by(tankID, recording, behavior, treatment, sex) %>%
                 summarize(duration_s = mean(duration_s),
                           behav_count = as.numeric(table(behavior)))
shortclay_coll <- shortclay_all %>%
                 group_by(tankID, recording, behavior, treatment) %>%
                 summarize(duration_s = mean(duration_s),
                           behav_count = as.numeric(table(behavior)))
dyestir_coll <- dyestir_all %>%
               group_by(tankID, recording, behavior, treatment) %>%
               summarize(duration_s = mean(duration_s),
                         behav_count = as.numeric(table(behavior)))
nostir_coll <- nostir_all %>%
               group_by(tankID, recording, behavior, treatment) %>%
               summarize(duration_s = mean(duration_s),
                         behav_count = as.numeric(table(behavior)))

#creating additional rows that aggregate together all of the behaviors to
#investigate overall behavioral trends
longclay_sum <- aggregate(cbind(duration_s, behav_count) ~ tankID + recording +
                                treatment + sex, data = longclay_coll,
                                FUN = "sum")
shortclay_sum <- aggregate(cbind(duration_s, behav_count) ~ tankID + recording +
                                 treatment, data = shortclay_coll, FUN = "sum")
dyestir_sum <- aggregate(cbind(duration_s, behav_count) ~ tankID + recording +
                               treatment, data = dyestir_coll, FUN = "sum")
nostir_sum <- aggregate(cbind(duration_s, behav_count) ~ tankID + recording +
                              treatment, data = nostir_coll, FUN = "sum")
#adding the summed rows to the main dataframes
longclay_agg <- rbind(longclay_coll, longclay_sum)
shortclay_agg <- rbind(shortclay_coll, shortclay_sum)
dyestir_agg <- rbind(dyestir_coll, dyestir_sum)
nostir_agg <- rbind(nostir_coll, nostir_sum)
#renaming the NA behavior labels from the summed dataframe
longclay_agg$behavior[is.na(longclay_agg$behavior)] <- "all"
shortclay_agg$behavior[is.na(shortclay_agg$behavior)] <- "all"
dyestir_agg$behavior[is.na(dyestir_agg$behavior)] <- "all"
nostir_agg$behavior[is.na(nostir_agg$behavior)] <- "all"

#creating additional rows that aggregate together just the aggressive behaviors
#this time to investigate overall trends in aggression
longclay_angr <- longclay_coll %>%
                filter(behavior %in% c("chasing", "lat_display",
                                       "agg_contact")) %>%
                aggregate(cbind(duration_s, behav_count) ~ tankID + recording +
                                treatment + sex, FUN = "sum")
shortclay_angr <- shortclay_coll %>%
                 filter(behavior %in% c("chasing", "lat_display",
                                       "agg_contact")) %>%
                 aggregate(cbind(duration_s, behav_count) ~ tankID + recording +
                                 treatment, FUN = "sum")
dyestir_angr <- dyestir_coll %>%
               filter(behavior %in% c("chasing", "lat_display",
                                     "agg_contact")) %>%
               aggregate(cbind(duration_s, behav_count) ~ tankID + recording +
                               treatment, FUN = "sum")
nostir_angr <- nostir_coll %>%
              filter(behavior %in% c("chasing", "lat_display",
                                     "agg_contact")) %>%
              aggregate(cbind(duration_s, behav_count) ~ tankID + recording +
                              treatment, FUN = "sum")
#adding the summed rows to the main dataframes
longclay_agg <- rbind(longclay_agg, longclay_angr)
shortclay_agg <- rbind(shortclay_agg, shortclay_angr)
dyestir_agg <- rbind(dyestir_agg, dyestir_angr)
nostir_agg <- rbind(nostir_agg, nostir_angr)
#renaming the NA behavior labels from the summed dataframe
longclay_agg$behavior[is.na(longclay_agg$behavior)] <- "all_aggression"
shortclay_agg$behavior[is.na(shortclay_agg$behavior)] <- "all_aggression"
dyestir_agg$behavior[is.na(dyestir_agg$behavior)] <- "all_aggression"
nostir_agg$behavior[is.na(nostir_agg$behavior)] <- "all_aggression"

#writing the dataframes to .csv
write_csv(longclay_agg, "chronic_clay_BORIS_all.csv")
write_csv(shortclay_agg, "acute_clay_BORIS_all.csv")
write_csv(dyestir_agg, "stir_dye_BORIS_all.csv")
write_csv(nostir_agg, "nostir_dye_BORIS_all.csv")
```