---
title: "Statistical Analyses of TRex Movement Data"
author: "Hannah Anderson"
date: "2023-06-26"
output: pdf_document
editor_options: 
  chunk_output_type: console
---


## Setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

setwd("C://Users/hande/Documents/R/fluctuating-turbidity")
library(tidyverse)
library(glmmTMB)
library(emmeans)
library(car)
library(DHARMa)
library(broom)

#importing the data
#chronic_clay <- read_csv("chronic_clay_movement_data.csv")
clay_dye <- read_csv("comparison_clay_dye_movement_data.csv")
dye_dye <- read_csv("comparison_dye_dye_movement_data.csv")
```


## Analyses for Experiment 1: Chronic (Two Week) Clay Exposure

```{r chronic clay}
#models including all recordings
chron_mean_speed <- glmmTMB(mean_speed ~ treatment*sex + (1|tankID),
                       data = chronic_clay, family = gaussian())
chron_var_speed <- update(chron_mean_speed, speed_variance ~ .)
chron_activratio <- update(chron_mean_speed, activity_ratio ~ .)
chron_tot_dist <- update(chron_mean_speed, totaldist_cm ~ .)
chron_max_speed <- update(chron_mean_speed, max_speed ~ .)
chron_max_accel <- update(chron_mean_speed, max_acceleration ~ .)

#checking model assumptions
plot(simulateResiduals(fittedModel = chron_mean_speed))
plot(simulateResiduals(fittedModel = chron_var_speed)) #assumptions not met
plot(simulateResiduals(fittedModel = chron_activratio))
plot(simulateResiduals(fittedModel = chron_tot_dist))
plot(simulateResiduals(fittedModel = chron_max_speed)) #assumptions not met
plot(simulateResiduals(fittedModel = chron_max_accel))

#transforming the data to meet model assumptions
chronic_trans <- chronic_clay
chronic_trans$speed_variance <- log(chronic_trans$speed_variance+1)
chronic_trans$max_speed <- log(chronic_trans$max_speed+1)

#the transformed models
chrolog_var_speed <- update(chron_var_speed, data = chronic_trans)
chrolog_max_speed <- update(chron_max_speed, data = chronic_trans)

#checking the transformed model assumptions
plot(simulateResiduals(fittedModel = chrolog_var_speed))
plot(simulateResiduals(fittedModel = chrolog_max_speed))

#analyzing the results
Anova(chron_mean_speed)
Anova(chrolog_var_speed)
Anova(chron_activratio)
Anova(chron_tot_dist)
Anova(chrolog_max_speed)
Anova(chron_max_accel)

#post hoc pairwise comparison of the significant results
chrolog_var_speed %>% emmeans(pairwise ~ treatment)
```


## Direct Comparisons

```{r direct}
#sub-setting the data to only include recording 4
direct_claydye <- clay_dye %>%
                  filter(recording == "rec4")
direct_dyedye <- dye_dye %>%
                filter(recording == "rec4")


#the clay vs dye models

#mean speed
d_claydye_speed <- lm(mean_speed ~ treatment*experiment, data = direct_claydye)
#maximum speed
d_claydye_maxsp <- update(d_claydye_speed, max_speed ~ .)
#activity ratio
d_claydye_activ <- update(d_claydye_speed, activity_ratio ~ .)
#maximum acceleration
d_claydye_accel <- update(d_claydye_speed, max_acceleration ~ .)
#total distance traveled
d_claydye_dist <- update(d_claydye_speed, totaldist_cm ~ .)

#checking the model assumptions
plot(d_claydye_speed)
plot(d_claydye_maxsp)
plot(d_claydye_activ) #assumptions not met
plot(d_claydye_accel)
plot(d_claydye_dist)

#using an alternative regression family to meet model assumptions
beta_d_claydye_activ <- glmmTMB(activity_ratio ~ treatment*experiment,
                                 data = direct_claydye, family = ordbeta(
                                                               link = "logit"))

#checking the assumptions of the GLM
plot(simulateResiduals(fittedModel = beta_d_claydye_activ))


#the stirred vs unstirred dye models

#mean speed
d_dyedye_speed <- lm(mean_speed ~ treatment*experiment, data = direct_dyedye)
#maximum speed
d_dyedye_maxsp <- update(d_dyedye_speed, max_speed ~ .)
#activity ratio
d_dyedye_activ <- update(d_dyedye_speed, activity_ratio ~ .)
#maximum acceleration
d_dyedye_accel <- update(d_dyedye_speed, max_acceleration ~ .)
#total distance traveled
d_dyedye_dist <- update(d_dyedye_speed, totaldist_cm ~ .)

#checking the model assumptions
plot(d_dyedye_speed)
plot(d_dyedye_maxsp)
plot(d_dyedye_activ) #assumptions not met
plot(d_dyedye_accel)
plot(d_dyedye_dist)

#using an alternative regression family to meet model assumptions for activity
beta_d_dyedye_activ <- glmmTMB(activity_ratio ~ treatment*experiment,
                                 data = direct_dyedye, family = ordbeta(
                                                               link = "logit"))

#checking the assumptions of the GLM
plot(simulateResiduals(fittedModel = beta_d_dyedye_activ))


#analyzing the results of the LMs and putting them in tibbles within a list for
#easy export
results_lm <- list()
results_lm[[1]] <- tidy(Anova(d_claydye_speed))
results_lm[[2]] <- tidy(Anova(d_claydye_maxsp))
results_lm[[3]] <- tidy(Anova(d_claydye_accel))
results_lm[[4]] <- tidy(Anova(d_claydye_dist))
results_lm[[5]] <- tidy(Anova(d_dyedye_speed))
results_lm[[6]] <- tidy(Anova(d_dyedye_maxsp))
results_lm[[7]] <- tidy(Anova(d_dyedye_accel))
results_lm[[8]] <- tidy(Anova(d_dyedye_dist))

#adding columns with additional identifying information to all tibbles within
#the results list
dependent_variables <- c("mean_speed", "max_speed", "max_acceleration",
                   "total_distance","mean_speed", "max_speed",
                   "max_acceleration", "total_distance")
for (i in 1:4) {
  results_lm[[i]]$experiments <- "claydye"
  results_lm[[i]]$dependent_variable <- dependent_variables[[i]]
}
for (i in 5:8) {
  results_lm[[i]]$experiments <- "dyedye"
  results_lm[[i]]$dependent_variable <- dependent_variables[[i]]
}
#combining the LM results list into a single tibble
results_lm_coll <- do.call(rbind, results_lm)
#reordering the columns to be more intuitive
results_lm_coll <- results_lm_coll %>%
                   select(experiments, dependent_variable, term, sumsq, df,
                          statistic, p.value)

#doing the same for the GLMs as with the LMs
results_glm <- list()
results_glm[[1]] <- tidy(Anova(beta_d_claydye_activ))
results_glm[[2]] <- tidy(Anova(beta_d_dyedye_activ))
results_glm[[1]]$experiments <- "claydye"
results_glm[[2]]$experiments <- "dyedye"
for (i in 1:2) {
  results_glm[[i]]$dependent_variable <- "activity_ratio"
}
results_glm_coll <- do.call(rbind, results_glm)
results_glm_coll <- results_glm_coll %>%
                    select(experiments, dependent_variable, term, df, statistic,
                           p.value)

#post hoc pairwise comparisons of the significant results
pair_lm <- list()
pair_lm[[1]] <- as.data.frame(pairs(emmeans(d_claydye_speed, ~ treatment),
                                    combine = TRUE))
pair_lm[[2]] <- as.data.frame(pairs(emmeans(d_claydye_maxsp, ~ treatment),
                                    combine = TRUE))
pair_lm[[3]] <- as.data.frame(pairs(emmeans(d_claydye_dist, ~ treatment),
                                    combine = TRUE))
pair_lm[[4]] <- as.data.frame(pairs(emmeans(d_dyedye_speed, ~ treatment),
                                    combine = TRUE))

dependent_variables <- c("mean_speed", "max_speed", "total_distance")
for (i in 1:3) {
  pair_lm[[i]]$experiments <- "claydye"
  pair_lm[[i]]$dependent_variable <- dependent_variables[[i]]
}
pair_lm[[4]]$experiments <- "dyedye"
pair_lm[[4]]$dependent_variable <- "mean_speed"
pair_lm_coll <- do.call(rbind, pair_lm)
pair_lm_coll <- pair_lm_coll %>%
                select(experiments, dependent_variable, everything())


#exporting the results to .csv
write_csv(results_lm_coll, "direct_comparison_movement_LMs.csv")
write_csv(results_glm_coll, "direct_comparison_movement_GLMs.csv")
write_csv(pair_lm_coll, "direct_pairwise_movement_LMs.csv")
```


## Full Comparisons

```{r full}
#averaging together the two morning recordings for each measure and for each
#experiment by comparison (clay/dye, dye stirred/dye unstirred)
morn_claydye <- clay_dye %>%
                filter(recording %in% c("rec1", "rec3")) %>%
                select(-recording) %>%
                group_by(shoalID, treatment, experiment) %>%
                summarize(mean_speed = mean(mean_speed),
                          max_speed = mean(max_speed),
                          activity_ratio = mean(activity_ratio),
                          max_acceleration = mean(max_acceleration),
                          totaldist_cm = mean(totaldist_cm))
morn_dyedye <- dye_dye %>%
               filter(recording %in% c("rec1", "rec3")) %>%
               select(-recording) %>%
               group_by(shoalID, treatment, experiment) %>%
               summarize(mean_speed = mean(mean_speed),
                         max_speed = mean(max_speed),
                         activity_ratio = mean(activity_ratio),
                         max_acceleration = mean(max_acceleration),
                         totaldist_cm = mean(totaldist_cm))
#labeling these values as the morning values
morn_claydye$time <- "morning"
morn_dyedye$time <- "morning"
#averaging together the afternoon values
afte_claydye <- clay_dye %>%
                filter(recording %in% c("rec2", "rec4")) %>%
                select(-recording) %>%
                group_by(shoalID, treatment, experiment) %>%
                summarize(mean_speed = mean(mean_speed),
                          max_speed = mean(max_speed),
                          activity_ratio = mean(activity_ratio),
                          max_acceleration = mean(max_acceleration),
                          totaldist_cm = mean(totaldist_cm))
afte_dyedye <- dye_dye %>%
               filter(recording %in% c("rec2", "rec4")) %>%
               select(-recording) %>%
               group_by(shoalID, treatment, experiment) %>%
               summarize(mean_speed = mean(mean_speed),
                         max_speed = mean(max_speed),
                         activity_ratio = mean(activity_ratio),
                         max_acceleration = mean(max_acceleration),
                         totaldist_cm = mean(totaldist_cm))
#labeling these values as the afternoon values
afte_claydye$time <- "afternoon"
afte_dyedye$time <- "afternoon"
#combining the averaged morning and afternoon values into a single dataframe
#for each two-experiment comparison
full_claydye <- rbind(morn_claydye, afte_claydye)
full_dyedye <- rbind(morn_dyedye, afte_dyedye)


#the clay vs dye models

#mean speed
claydye_speed <- glmmTMB(mean_speed ~ treatment*experiment*time + (1|shoalID),
                         data = full_claydye)
#maximum speed
claydye_maxsp <- update(claydye_speed, max_speed ~ .)
#activity ratio
claydye_activ <- update(claydye_speed, activity_ratio ~ .)
#maximum acceleration
claydye_accel <- update(claydye_speed, max_acceleration ~ .)
#total distance traveled
claydye_dist <- update(claydye_speed, totaldist_cm ~ .)

#testing model assumptions
plot(simulateResiduals(fittedModel = claydye_speed))
plot(simulateResiduals(fittedModel = claydye_maxsp))
plot(simulateResiduals(fittedModel = claydye_activ)) #assumptions not met
plot(simulateResiduals(fittedModel = claydye_accel))
plot(simulateResiduals(fittedModel = claydye_dist))

#using an alternative regression family to meet model assumptions
beta_claydye_activ <- update(claydye_activ, . ~ ., family = ordbeta(link =
                                                                    "logit"))

#checking the assumptions of the GLM
plot(simulateResiduals(fittedModel = beta_claydye_activ))


#the stirred vs unstirred dye models

#mean speed
dyedye_speed <- glmmTMB(mean_speed ~ treatment*experiment*time + (1|shoalID),
                         data = full_dyedye)
#maximum speed
dyedye_maxsp <- update(dyedye_speed, max_speed ~ .)
#activity ratio
dyedye_activ <- update(dyedye_speed, activity_ratio ~ .)
#maximum acceleration
dyedye_accel <- update(dyedye_speed, max_acceleration ~ .)
#total distance traveled
dyedye_dist <- update(dyedye_speed, totaldist_cm ~ .)

#testing model assumptions
plot(simulateResiduals(fittedModel = dyedye_speed))
plot(simulateResiduals(fittedModel = dyedye_maxsp)) #assumptions not met
plot(simulateResiduals(fittedModel = dyedye_activ)) #assumptions not met
plot(simulateResiduals(fittedModel = dyedye_accel))
plot(simulateResiduals(fittedModel = dyedye_dist))

#transforming the data to meet model assumptions
trans_full_dye <- full_dyedye
trans_full_dye$max_speed <- log(trans_full_dye$max_speed)

#the transformed model
trans_dyedye_maxsp <- update(dyedye_maxsp, . ~ ., data = trans_full_dye)

#checking the transformed model assumptions
plot(simulateResiduals(fittedModel = trans_dyedye_maxsp))

#using an alternative regression family to meet model assumptions
beta_dyedye_activ <- update(dyedye_activ, . ~ ., family = ordbeta(link =
                                                                  "logit"))

#checking the assumptions of the GLM
plot(simulateResiduals(fittedModel = beta_dyedye_activ))


#analyzing the results of the LMMs and putting them in tibbles within a list for
#easy export
results_lmm <- list()
results_lmm[[1]] <- tidy(Anova(claydye_speed))
results_lmm[[2]] <- tidy(Anova(claydye_maxsp))
results_lmm[[3]] <- tidy(Anova(claydye_accel))
results_lmm[[4]] <- tidy(Anova(claydye_dist))
results_lmm[[5]] <- tidy(Anova(dyedye_speed))
results_lmm[[6]] <- tidy(Anova(trans_dyedye_maxsp))
results_lmm[[7]] <- tidy(Anova(dyedye_accel))
results_lmm[[8]] <- tidy(Anova(dyedye_dist))

#adding columns with additional identifying information to all tibbles within
#the results list
dependent_variables <- c("mean_speed", "max_speed", "max_acceleration",
                   "total_distance","mean_speed", "max_speed",
                   "max_acceleration", "total_distance")
for (i in 1:4) {
  results_lmm[[i]]$experiments <- "claydye"
  results_lmm[[i]]$dependent_variable <- dependent_variables[[i]]
}
for (i in 5:8) {
  results_lmm[[i]]$experiments <- "dyedye"
  results_lmm[[i]]$dependent_variable <- dependent_variables[[i]]
}
#combining the LMM results list into a single tibble
results_lmm_coll <- do.call(rbind, results_lmm)
#reordering the columns to be more intuitive
results_lmm_coll <- results_lmm_coll %>%
                    select(experiments, dependent_variable, term, df, statistic,
                           p.value)

#doing the same for the GLMMs as with the LMMs
results_glmm <- list()
results_glmm[[1]] <- tidy(Anova(beta_claydye_activ))
results_glmm[[2]] <- tidy(Anova(beta_dyedye_activ))
results_glmm[[1]]$experiments <- "claydye"
results_glmm[[2]]$experiments <- "dyedye"
for (i in 1:2) {
  results_glmm[[i]]$dependent_variable <- "activity_ratio"
}
results_glmm_coll <- do.call(rbind, results_glmm)
results_glmm_coll <- results_glmm_coll %>%
                     select(experiments, dependent_variable, term, df, statistic,
                           p.value)

#post hoc pairwise comparisons of the significant LMM results
pair_lmm <- list()
pair_lmm[[1]] <- as.data.frame(pairs(emmeans(claydye_speed, ~ treatment |
                                                              experiment |
                                                              time)))
pair_lmm[[2]] <- as.data.frame(pairs(emmeans(claydye_maxsp, ~ treatment |
                                                              time)))
pair_lmm[[3]] <- as.data.frame(pairs(emmeans(claydye_dist, ~ treatment |
                                                             experiment |
                                                             time)))
pair_lmm[[4]] <- as.data.frame(pairs(emmeans(dyedye_speed, ~ treatment | time)))
pair_lmm[[5]] <- as.data.frame(pairs(emmeans(dyedye_activ, ~ treatment)))
pair_lmm[[6]] <- as.data.frame(pairs(emmeans(dyedye_dist, ~ treatment | time)))

for (i in 1:3) {
  pair_lmm[[i]]$experiments <- "claydye"
}
for (i in 4:6) {
  pair_lmm[[i]]$experiments <- "dyedye"
}
pair_lmm[[1]]$dependent_variable <- "mean_speed"
pair_lmm[[2]]$dependent_variable <- "max_speed"
pair_lmm[[3]]$dependent_variable <- "total_distance"
pair_lmm[[4]]$dependent_variable <- "mean_speed"
pair_lmm[[5]]$dependent_variable <- "activity_ratio"
pair_lmm[[6]]$dependent_variable <- "total_distance"
pair_lmm_coll_three <- rbind(pair_lmm[[1]], pair_lmm[[3]])
pair_lmm_coll_two <- rbind(pair_lmm[[2]], pair_lmm[[4]])
pair_lmm_coll_two <- rbind(pair_lmm_coll_two, pair_lmm[[6]])
pair_lmm_coll_three <- pair_lmm_coll_three %>%
                       select(experiments, dependent_variable, everything())
pair_lmm_coll_three <- pair_lmm_coll_two %>%
                       select(experiments, dependent_variable, everything())

#post hoc pairwise comparisons of the significant GLMM result
pair_glmm <- as.data.frame(pairs(emmeans(beta_claydye_activ, ~ treatment)))
pair_glmm$experiments <- "claydye"
pair_glmm$dependent_variable <- "activity_ratio"
pair_glmm <- pair_glmm %>%
             select(experiments, dependent_variable, estimate, SE, df, z.ratio,
                    p.value)


#exporting the results to .csv
write_csv(results_lmm_coll, "full_comparison_movement_LMMs.csv")
write_csv(results_glmm_coll, "full_comparison_movement_GLMMs.csv")
write_csv(pair_lmm_coll_three, "full_pairwise_threeway_interaction_LMMs.csv")
write_csv(pair_lmm_coll_two, "full_pairwise_twoway_interaction_LMMs.csv")
write_csv(pair_lmm[[5]], "full_pairwise_no_interaction_LMMs.csv")
write_csv(pair_glmm, "full_pairwise_comparison_movement_GLMMs.csv")
```